### ISSUE TITLE
solve captcha

### ISSUE THREAD

**Issue by ApoCringe** [Silpux/GrowCastleAutobot#1]
bot can't solve new captcha

**Comment by Silpux** [comment]
im trying to make something to it, but it seems like it has increasing difficulty, or different people just get different versions of it. Hard to test

**Comment by ApoCringe** [comment]
as for the random types of captchas for different people, it may be so, but i always have the same one.
i solve it using AnyDesk on my phone when i'm away from my pc (maybe it will help someone)

**Comment by ApoCringe** [comment]
![image](https://github.com/user-attachments/assets/cefb6530-3014-42c0-ab13-f36ef03f84fd)

**Comment by Silpux** [comment]
> ![image](https://private-user-images.githubusercontent.com/130511781/361147465-cefb6530-3014-42c0-ab13-f36ef03f84fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTEyMDYsIm5iZiI6MTcyNDUxMDkwNiwicGF0aCI6Ii8xMzA1MTE3ODEvMzYxMTQ3NDY1LWNlZmI2NTMwLTMwMTQtNDJjMC1hYjEzLWYzNmVmMDNmODRmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNDQ4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzMyZmQ1NzZmYzUwYjUzZjEwN2Y0NDkzMmM2Zjk3ZGJiYWViZDQzMzcwOThiMDM4NDlhY2ZkMWM4MzI3YWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rq0zf7ZSkDA-ce81odGzva1emr-5TQYIRnU7k0LE4l0)


We all have the same thing, but someone has only the right thing spinning, and someone has all spinning when they shuffle. The right one makes 6-7 spins, and others 1-3.

**Comment by Silpux** [comment]
I don't have any working idea for script that will solve all captcha difficulty levels.

**Comment by monstergvg** [comment]
Молодец парень, что смог пификсить, я тобой очень сильно горжусь)
![image](https://github.com/user-attachments/assets/1d4b9588-114d-48c8-96f4-2796bec5f665)

**Comment by monstergvg** [comment]
и я надеюсь ты понимаешь русский язык) так как в ноксе у тебя русский интерфейс

**Comment by monstergvg** [comment]
а и ещё, я как веб разраб отлично понимаю что тебе сейчас впадлу и лень будет и ты в любом случае будешь прав, но можешь после того как хорошенько отдохнёшь решить проблему с айс магом так как он не нажимается в область врагов а просто весит в воздухе)
буду очень благодарен.(он кстати не только с айс магом работает но и с лайт магом)
![image](https://github.com/user-attachments/assets/46ddac0d-8119-4388-b4df-dd0f29d314f0)

**Comment by Silpux** [comment]
@ApoCringe try captcha solver now. I modified bunch of files, so double check that you have the most recent versions of them. If it solves with good success rate, you can close issue.

**Comment by Silpux** [comment]
@monstergvg Для героев с прицелами в инструкции есть пункт про то как сделать чтобы они прожимались. Там 2 строчки нужно в правильном месте дописать.
Это уже не актуально, бо играть вручную сейчас опасно, за это быстро банят, и кроме того этот прицел будет тратить время каждый раз.

**Comment by ApoCringe** [comment]
@Silpux thx, great work.
