### ISSUE TITLE
error expand 304

### ISSUE THREAD

**Issue by jinjinjarasa** [Silpux/GrowCastleAutobot#3]
after all setup, open clickermann and hit the green play button
![image](https://github.com/user-attachments/assets/28eff923-b712-4b15-bfbb-b08f9ccef4ca)
this popup occurs and dont play

**Comment by Silpux** [comment]
@jinjinjarasa This happens because you have 125% scale on your screen. Go to settings -> Display settings -> Set Scale and layout from 125% to 100%

**Comment by jinjinjarasa** [comment]
@Silpux it works very well thank you very much have a good day
