### ISSUE TITLE
Clickermann x64 doesn't work for me.

### ISSUE THREAD

**Issue by champ101299** [Silpux/GrowCastleAutobot#4]
Sorry, I'm not good at English.

When I first downloaded it, it can be used normally. But after I restart my computer, it doesn't work. Even if I delete it and download it again, it still doesn't work. So I tried downloading Clickermann X32 it worked, but it can't use the Captcha solving function.It shows error while calling dll. Expected 69, but was 0 (I'm sure slpx.exe, solver.dll and opencv_world490.dll are in Clicker's core folder.)

I tried Clickermann x64 which has the same settings as Clickermann x32 which can be used, but Clickermann x64 still doesn't work.

This is the Clickermann x64 log after execution.
![Screenshot 2024-10-22 175248](https://github.com/user-attachments/assets/af66854a-bde5-440b-9aac-872c3bde5a90)

**Comment by Silpux** [comment]
@champ101299 Hi
Message me on discord: @silpux
If it worked first time, then maybe theres something wrong when configuring it. But there also may be bugs. I can't tell exactly right now

**Comment by champ101299** [comment]
How do I send you a message?

**Comment by Silpux** [comment]
Do you have discord?

**Comment by Silpux** [comment]
Send me friend request

**Comment by Silpux** [comment]
Or tell your @
