### ISSUE TITLE
Добавь авто сбор мимиков

### ISSUE THREAD

**Issue by xFunt1k** [Silpux/GrowCastleAutobot#5]
Полезная ведь тема

**Comment by Silpux** [comment]
@xFunt1k Если ты не менял в настройках ничего, связанное с мимиком, то он должен был собирать их.
У меня собирает

**Comment by Silpux** [comment]
Поменял немного его нахождение, пробуй сейчас

**Comment by xFunt1k** [comment]
![image](https://github.com/user-attachments/assets/c8c9d923-6f80-4eef-8bea-d5e818ec2c3f)
Спасибо, теперь работает)

**Comment by xFunt1k** [comment]
Может ли кстати на эту механику повлиять то, что я в прямом эфире вносил изменения в макрос?
Хотя я и не видел, чтобы это была переключаемая функция

**Comment by Silpux** [comment]
Менять код, когда он играет, не получится. А если ты меняешь настройки кликера, когда он играет, то он только меняет файл _main_settings.txt, а он считывается только когда ты запускаешь кликер.
Там есть переменная $mimic_collect_percent. В ней ты можешь указать шанс на собирание мимика, чтобы не собирались все постоянно

**Comment by xFunt1k** [comment]
Вот либо оно по умолчанию не все собирает, тогда писало бы лучше, что мимик но коллект, либо оно просто криво работает, ибо вообще не собирает снова.
![image](https://github.com/user-attachments/assets/b13d90f2-b6c0-4e3d-816c-83433494c03c)

**Comment by xFunt1k** [comment]
Он 100%, но не собирает...
![image](https://github.com/user-attachments/assets/d5603de9-d398-4014-8223-098fb6ff10ab)

**Comment by xFunt1k** [comment]
Будто не знает про некоторые позиции

**Comment by xFunt1k** [comment]
С мимиками зашибумба, но время от времени когда смотрит рекламу мискликает по покупке за реал, нокс сворачивается в вертикальный режим и вылазит платёжка гугла, что ломает сценарий.
Так же иногда просто игра закрывается, сидишь в главном меню телефона и ничего не происходит.
Иногда рекламу не досматривает, сворачивает игру и очищает из недавних, мб это и есть причина вылета в главное меню, не знаю ибо скрипт в свёрнутом режиме пашет, нет времени всё досконально изучать.

**Comment by Silpux** [comment]
@xFunt1k похоже на то, что тебе надо добавить задержки после кликов, потому что когда делается рестарт, скрипт сразу кликает по гк. Если он не открылся, значит клик произошел до того, как гк стал кликабельным.
На счет реклам, когда не досматривает и делает перезаход, то это может быть изза того, что рекламу невозможно закрыть правым кликом мыши, а скрипт их закрывает только так. Если обязательно надо найти крестик и закрыть, то скрипт этого не сделает, так как эти крестики могут быть непонятно где и иметь разный вид.

(я надеюсь что у тебя всё изначально правильно настроено: гк стоит в правильной клеточке в меню, и правая кнопка мыши делает ход назад)

**Comment by xFunt1k** [comment]
У рекламы таймер с минуту там идёт, остаётся 27 секунд - бб, закрываем игру

**Comment by xFunt1k** [comment]
Всегда крестики в 1 месте только наблюдал помоему

**Comment by xFunt1k** [comment]
Настроено всё правильно, если только запускаю скрипт, то он сам его открывает, кнопка назад на месте

**Comment by Silpux** [comment]
Там настроено ждать до 40 секунд где-то. В gc_bot_settings.txt есть настройка $fixed_ad_wait. Поставь там где-то 30, и тогда скрипт запустит таймер через 30 секунд

**Comment by Silpux** [comment]
на 30 секунд он зафризится после запуска рекламы

**Comment by xFunt1k** [comment]
Иногда чёто накликивает, то в прокачку персонажа зайдёт и там и остнется, то на автобатл нажмёт и тупит в этой менюшке

**Comment by Silpux** [comment]
Когда в прокачку героя заходит, то проверяет есть ли красная кнопка TAKE OFF. Там 4 пикселя должны совпадать. Проверь еще раз, стоит ли у тебя ход назад с пкм

**Comment by Silpux** [comment]
Когда кликаешь пкм, то должно происходить тоже самое, что если бы ты нажал ескейп

**Comment by Silpux** [comment]
По поводу застреваний в меню АБ, то в gc_bot_settings.txt есть вот эти переменные:
```
$battle_click_wait_ms = 80

$wait_before_AB_open = 0.05
$wait_after_AB_open = 0.05
$wait_after_gab_open = 0.05
```

Их увеличь раза в 2-3, и пробуй как будет

**Comment by xFunt1k** [comment]
Где можно поменять Smith II на Stos, который чаще чинит, но меньше? Где задать, чтобы при нехватке 30% прожимал его...

**Comment by xFunt1k** [comment]
И додумать бы уже механику с ледяным магом и подобными ему юнитами, которых нужно направлять. Типо сделать в меню выбора кликабельных персонажей позицию, куда будут жать такие персонажи, чтобы игрок сам это продумывал, а скрипт только кликал куда игрок скажет.

**Comment by xFunt1k** [comment]
Добавить бы ещё авто крафт фиол пыли в кузне

**Comment by Silpux** [comment]
> Где можно поменять Smith II на Stos, который чаще чинит, но меньше? Где задать, чтобы при нехватке 30% прожимал его...

Скрипт не отличает смита от стоса. Он только смотрит на синие полоски над персонажами. Того персонажа, которого ты отметил как смит он будет кликать когда определённый пиксель хп бара будет чёрным. Его положение можно поменять в `gc_bot_lib.txt` в функции `ActivateHeroes` или `ActivateHeroesDun` - это две разные фукции для прожатий героев на волне или на данжах.

**Comment by Silpux** [comment]
> И додумать бы уже механику с ледяным магом и подобными ему юнитами, которых нужно направлять. Типо сделать в меню выбора кликабельных персонажей позицию, куда будут жать такие персонажи, чтобы игрок сам это продумывал, а скрипт только кликал куда игрок скажет.

Как задать дополнительный клик после прожатия конкретного персонажа я описал в инструкции. Оно будет лагать у разных людей, и только время тратить. Лучше пусть сами люди настраивают себе.

**Comment by Silpux** [comment]
> Добавить бы ещё авто крафт фиол пыли в кузне и автопрокачку частей замка и героев за алмазы без боя, чисто в афк стоя без волн (через гг время ускорить в 100 раз и збс)))

Автокрафт пыли я не планирую делать. Я бы хотел двигаться в сторону уменьшения вероятности быть забаненым.
Если слишком нужно прокачивать замок и персов с ускорением, то можешь в `gc_bot_main` заменить вызов `Replay` на это:
```
$replaysforupg = 100
wait(30)
```
Тогда будет стоять в меню и прокачивать раз в 30 секунд то, что указано в настройках

**Comment by Silpux** [comment]
Код кликера открыт, его можно вообще переписать как хочешь. Не обязательно меня просить сделать какие-то простенькие фичи, которые никто не будет использовать, кроме тебя

**Comment by xFunt1k** [comment]
Я слишком глупый для этого, можешь хотя бы текстом объяснить как это сделать, если не хочешь официально добавлять. Я бы на твоём месте просто делал и фулл безопасную версию и фулл напичканную всем чем только можно с предупреждениями, что за 2 забанят атятя

**Comment by Silpux** [comment]
```
lclick(<координаты кнопки TO TOWN>)
wait(1)
lclick(<координаты кузни>)
wait(2)
lclick(<координаты кнопки крафта пыли>)
wait(3)
lclick(<координаты кнопки закрытия кузни>)
wait(1)
lclick(<координаты кнопки TO TOWN>)
```
Это вставить в ту область кода, где кликер находится в меню гк, и пробовать тестить, и поправлять если надо
